{{- if .Values.githubAppCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "safe-settings.fullname" . }}-app-credentials
type: Opaque
data:
  APP_ID: {{ required "A valid githubAppCredentials.appId is required!" .Values.githubAppCredentials.appId | toString | b64enc }}
  PRIVATE_KEY: {{ required "A valid githubAppCredentials.privateKey is required!" .Values.githubAppCredentials.privateKey | toString | b64enc }}
  WEBHOOK_SECRET: {{ required "A valid githubAppCredentials.wehookSecret is required!" .Values.githubAppCredentials.webhookSecret | toString | b64enc }}
{{- end }}
